Fixing incorrect handling of error situations in init script
Major problems should break stacking instead of
just printing error message.

- error values are now correctly propagated
- removing confusing/not-working local die function

Closes-bug: 1512967
Change-Id: I9e67b960e5cbf3784ad4eb734cf9884f119cc076

diff --git a/devstack/ovs-dpdk/ovs-dpdk-init b/devstack/ovs-dpdk/ovs-dpdk-init
--- a/devstack/ovs-dpdk/ovs-dpdk-init
+++ b/devstack/ovs-dpdk/ovs-dpdk-init
@@ -16,7 +16,6 @@ is_ubuntu(){
 # Prints line number and "message" in error format
 # err $LINENO "message"
 err() {
-    local exitcode=$?
     errXTRACE=$(set +o | grep xtrace)
     set +o xtrace
     local msg="[ERROR] ${BASH_SOURCE[2]}:$1 $2"
@@ -25,19 +24,6 @@ err() {
         echo $msg >> "${SCREEN_LOGDIR}/error.log"
     fi
     $errXTRACE
-    return $exitcode
-}
-
-# Prints line number and "message" then exits
-# die $LINENO "message"
-die() {
-    local exitcode=$?
-    set +o xtrace
-    local line=$1; shift
-     err $line "$*"
-    # Give buffers a second to flush
-    sleep 1
-    exit $exitcode
 }
 
 init_db(){
@@ -101,7 +87,7 @@ load_igb_uio_module(){
     echo "Loading DPDK UIO module"
     sudo insmod $RTE_SDK/$RTE_TARGET/kmod/igb_uio.ko
     if [ $? -ne 0 ] ; then
-        echo "## ERROR: Could not load kmod/igb_uio.ko."
+        err $LINENO "## ERROR: Could not load kmod/igb_uio.ko."
         exit 1
     fi
 }
@@ -274,14 +260,16 @@ check_nic_presence () {
     if [[ "$interfaces" =~ ": $nic: " ]]; then
         return 0
     fi
-    die "The nic interface $nic is not present in the system"
+    err $LINENO "The nic interface $nic is not present in the system"
+    exit 2
 }
 
 
 find_bridge() {
     # Check argument is supplied.
     if [[ -z "$1" ]]; then
-        die 'No argument supplied, nic expected'
+        err $LINENO "No argument supplied, nic expected"
+        exit 3
     fi
     if [[ -z "$2" ]]; then
         # OVS_DPDK_PORT_MAPPINGS not present, use the nic interface name
@@ -308,7 +296,8 @@ find_bridge() {
 add_bridges() {
     # Check argument is supplied.
     if [[ -z "$1" ]]; then
-        die 'No argument supplied, OVS_BRIDGE_MAPPINGS expected'
+        err $LINENO "No argument supplied, OVS_BRIDGE_MAPPINGS expected"
+        exit 4
     fi
 
     # Adds the OVS bridge, given the mapping list OVS_BRIDGE_MAPPINGS.
@@ -324,7 +313,8 @@ add_bridges() {
 bind_nic_2_ovsdriver() {
     # Check argument is supplied.
     if [[ -z "$1" ]]; then
-        die 'No argument supplied, PCI_ARRAY[@] expected'
+        err $LINENO "No argument supplied, PCI_ARRAY[@] expected"
+        exit 5
     fi
 
     list=("$@")
@@ -385,7 +375,8 @@ alloc_hugepages() {
     sudo mkdir -p $OVS_HUGEPAGE_MOUNT
 
     if [ $OVS_NUM_HUGEPAGES -eq 0 ]; then
-        die $LINENO "OVS_NUM_HUGEPAGES not set"
+        err $LINENO "OVS_NUM_HUGEPAGES not set"
+        exit 6
     fi
     grep -ws $OVS_HUGEPAGE_MOUNT /proc/mounts > /dev/null
 
@@ -548,7 +539,8 @@ start_ovs(){
         if [ -n "$OVS_LOCK_DIR" ]; then
             sudo rm -rf $OVS_LOCK_DIR
         fi
-        die $LINENO "ovs-vswitchd application failed to start $PID"
+        err $LINENO "ovs-vswitchd application failed to start $PID"
+        exit 7
     fi
     while [ ! $(grep "unix.*connected" ${OVS_LOG_DIR}/ovs-vswitchd.log) ]; do
         PID=$(pidof ovs-vswitchd)
@@ -560,7 +552,8 @@ start_ovs(){
             if [ -n "$OVS_LOCK_DIR" ]; then
                 sudo rm -rf $OVS_LOCK_DIR
             fi
-            die $LINENO "ovs-vswitchd application failed to start $PID"
+            err $LINENO "ovs-vswitchd application failed to start $PID"
+            exit 8
         fi
     done
     sudo rm -rf $OVS_LOCK_DIR
@@ -577,7 +570,8 @@ start_ovs(){
             ip link show $bridge
         done
         if [[ $counter -ge 120 ]]; then
-            die $LINENO "Interface $bridge not created!"
+            err $LINENO "Interface $bridge not created!"
+            exit 9
         fi
         sudo ip addr add $cidr dev $bridge
         sudo ip link set $bridge up
